"""VIGER Telegram bot: Python-only image SR + self-trained TinyGPT."""

from __future__ import annotations

import asyncio
import os
import shutil
import sys
import tempfile
import time
from pathlib import Path

from PIL import Image
from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.error import Conflict
from telegram.ext import Application, CallbackQueryHandler, CommandHandler, ContextTypes, MessageHandler, filters

# Make the repository root importable even when this file is launched directly.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

CORPUS = ROOT / "data" / "chat.txt"
LEARNING_CORPUS = ROOT / "data" / "user_learning.txt"
CHECKPOINT = ROOT / "artifacts" / "viger_tiny_lm.pt"

_lm = None
_sr = None


def keyboard() -> InlineKeyboardMarkup:
    return InlineKeyboardMarkup([
        [
            InlineKeyboardButton("✨ AI 2×", callback_data="scale:2"),
            InlineKeyboardButton("🔥 AI 4×", callback_data="scale:4"),
        ],
        [InlineKeyboardButton("🧠 AI status", callback_data="status")],
    ])


def get_scale(context: ContextTypes.DEFAULT_TYPE) -> int:
    return int(context.user_data.get("scale", 2))


def get_lm():
    global _lm
    if _lm is None:
        from python.viger_tiny_lm import load_or_train
        _lm = load_or_train(CHECKPOINT, CORPUS)
    return _lm


def reload_lm():
    global _lm
    from python.viger_tiny_lm import load_or_train
    _lm = load_or_train(CHECKPOINT, CORPUS)
    return _lm


def get_sr():
    global _sr
    if _sr is None:
        from python.sr_engine import SREngine
        _sr = SREngine()
    return _sr


def generate_text(text: str, history: list[tuple[str, str]]) -> str:
    from python.viger_tiny_lm import answer
    return answer(get_lm(), text, history=history)


def make_voice(text: str, path: Path) -> None:
    import pyttsx3
    engine = pyttsx3.init()
    engine.setProperty("rate", 165)
    engine.save_to_file(text, str(path))
    engine.runAndWait()


def append_learning_text(text: str) -> None:
    """Store user-provided language material without storing the bot's reply."""
    LEARNING_CORPUS.parent.mkdir(parents=True, exist_ok=True)
    clean = text.strip()
    if not clean:
        return
    with LEARNING_CORPUS.open("a", encoding="utf-8") as file:
        file.write(f"\n{clean}\n")


def learning_stats() -> tuple[int, int]:
    if not LEARNING_CORPUS.exists():
        return 0, 0
    text = LEARNING_CORPUS.read_text(encoding="utf-8", errors="ignore")
    non_empty = [line for line in text.splitlines() if line.strip()]
    return len(non_empty), len(text)


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    context.user_data["scale"] = 2
    context.user_data["voice"] = False
    context.user_data["history"] = []
    context.user_data["learn"] = False
    await update.message.reply_text(
        "⚡ VIGER AI lab\n\n"
        "📸 Photo → AI 2×/4× super-resolution.\n"
        "💬 Text → my own TinyGPT generates the answer.\n"
        "📚 /learn on|off stores your normal messages as language-training text.\n"
        "🧪 /teach question => answer adds supervised training data.\n"
        "🧠 /train [steps] retrains the model from scratch.\n"
        "🔊 /voice on|off enables local voice replies.\n\n"
        "Python-only: no Visual Studio, no C++, no .exe, no text LLM server.",
        reply_markup=keyboard(),
    )


async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    await update.message.reply_text(
        "📸 Photo: choose 2× or 4×, then send the image.\n"
        "💬 Text: generated by the self-trained TinyGPT.\n"
        "📚 /learn on|off — collect your next normal messages as language text.\n"
        "🧪 /teach question => answer — add a supervised example.\n"
        "🧠 /train or /train 5000\n"
        "🔊 /voice on|off\n"
        "ℹ️ /status\n\n"
        "When learning mode is ON, VIGER stores the text you send, but does not store its own replies."
    )


async def status_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    try:
        import torch
        device = "CUDA" if torch.cuda.is_available() else "CPU"
    except Exception:
        device = "unknown"

    lm_text = "not loaded"
    if _lm is not None:
        model, tokenizer = _lm
        params = sum(p.numel() for p in model.parameters())
        lm_text = f"TinyGPT v5 • {params:,} params • vocab {tokenizer.vocab_size}"

    lines, chars = learning_stats()
    await update.message.reply_text(
        f"🧠 TinyLM: {lm_text}\n"
        f"🖼️ SR: {'loaded' if _sr is not None else 'not loaded'}\n"
        f"⚙️ Device: {device}\n"
        f"📚 User learning text: {lines} lines / {chars} chars\n"
        "☁️ Text model: none downloaded\n"
        "🌐 Image model: pretrained Swin2SR weights, cached locally after first download"
    )


async def voice_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    value = (context.args[0].lower() if context.args else "on")
    context.user_data["voice"] = value in {"on", "1", "true", "yes"}
    state = "ON 🔊" if context.user_data["voice"] else "OFF"
    await update.message.reply_text(f"Voice: {state}")


async def learn_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    value = (context.args[0].lower() if context.args else "on")
    if value in {"on", "1", "true", "yes"}:
        context.user_data["learn"] = True
        await update.message.reply_text(
            "📚 Learning mode: ON\n"
            "Your normal text messages will be added to data/user_learning.txt.\n"
            "The bot's replies are NOT stored.\n"
            "When you are done, run /learn off, then /train."
        )
    elif value in {"off", "0", "false", "no"}:
        context.user_data["learn"] = False
        lines, chars = learning_stats()
        await update.message.reply_text(
            f"📚 Learning mode: OFF\nStored: {lines} lines / {chars} chars\n"
            "Run /train when you want the model to learn this material."
        )
    elif value == "stats":
        lines, chars = learning_stats()
        state = "ON" if context.user_data.get("learn", False) else "OFF"
        await update.message.reply_text(
            f"📚 Learning mode: {state}\nStored: {lines} lines / {chars} chars"
        )
    else:
        await update.message.reply_text("Use /learn on, /learn off, or /learn stats")


async def train_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    raw_steps = context.args[0] if context.args else "5000"
    try:
        steps = max(100, min(int(raw_steps), 10000))
    except ValueError:
        await update.message.reply_text("Use /train or /train 5000")
        return

    context.user_data["learn"] = False
    status = await update.message.reply_text(
        f"🧠 Training TinyGPT v5 from scratch…\nSteps: {steps}\nThis can take a while on CPU."
    )
    try:
        from python.viger_tiny_lm import train
        started = time.perf_counter()
        await asyncio.to_thread(train, CORPUS, CHECKPOINT, steps)
        await asyncio.to_thread(reload_lm)
        elapsed = time.perf_counter() - started
        await status.edit_text(f"✅ TinyGPT v5 retrained from scratch in {elapsed:.1f}s")
    except Exception as exc:
        await status.edit_text(f"❌ TinyGPT training failed.\n\n{type(exc).__name__}: {exc}")


async def teach_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    raw = " ".join(context.args).strip()
    if "=>" not in raw:
        await update.message.reply_text("Use: /teach question => answer")
        return

    question, response = (part.strip() for part in raw.split("=>", 1))
    if not question or not response:
        await update.message.reply_text("Both the question and answer are required.")
        return

    CORPUS.parent.mkdir(parents=True, exist_ok=True)
    with CORPUS.open("a", encoding="utf-8") as file:
        file.write(f"\n<USER> {question} <ASSISTANT> {response} <END>\n")

    CHECKPOINT.unlink(missing_ok=True)
    global _lm
    _lm = None
    await update.message.reply_text(
        "✅ Example added to the training corpus.\n"
        "Now run /train to teach TinyGPT on it."
    )


async def callback(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    query = update.callback_query
    await query.answer()
    data = query.data or ""
    if data.startswith("scale:"):
        scale = int(data.split(":", 1)[1])
        context.user_data["scale"] = scale
        await query.edit_message_text(
            f"✅ AI scale: {scale}×\nSend a photo.",
            reply_markup=keyboard(),
        )
    elif data == "status":
        device = "CPU"
        try:
            import torch
            if torch.cuda.is_available():
                device = "CUDA"
        except Exception:
            pass
        lines, chars = learning_stats()
        await query.edit_message_text(
            f"🧠 TinyGPT v5: {'loaded' if _lm is not None else 'will train on first message'}\n"
            f"🖼️ SR: {'loaded' if _sr is not None else 'will load on first photo'}\n"
            f"📚 Learning text: {lines} lines / {chars} chars\n"
            f"⚙️ Device: {device}",
            reply_markup=keyboard(),
        )


async def process_image(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.message
    if message is None:
        return
    scale = get_scale(context)
    workdir = Path(tempfile.mkdtemp(prefix="viger_sr_"))
    status = await message.reply_text(f"⚙️ AI super-resolution {scale}×…")
    try:
        if message.photo:
            telegram_file = await message.photo[-1].get_file()
            input_path = workdir / "input.jpg"
        elif message.document and message.document.mime_type and message.document.mime_type.startswith("image/"):
            telegram_file = await message.document.get_file()
            suffix = Path(message.document.file_name or "input.png").suffix.lower()
            if suffix not in {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tif", ".tiff"}:
                suffix = ".png"
            input_path = workdir / f"input{suffix}"
        else:
            return

        await telegram_file.download_to_drive(custom_path=str(input_path))
        image = Image.open(input_path).convert("RGB")
        started = time.perf_counter()
        engine = get_sr()
        output = await asyncio.to_thread(engine.enhance, image, scale)
        output_path = workdir / f"viger_ai_{scale}x.png"
        await asyncio.to_thread(engine.save_4k_or_less, output, output_path)
        elapsed = time.perf_counter() - started

        await status.delete()
        caption = (
            f"✨ VIGER AI SR\nScale: {scale}×\n"
            f"Output: {output.width}×{output.height}\n"
            f"Time: {elapsed:.2f}s\nModel: Swin2SR"
        )
        with output_path.open("rb") as file:
            await message.reply_document(document=file, filename=output_path.name, caption=caption)
    except Exception as exc:
        await status.edit_text(
            "❌ AI image processing failed.\n\n"
            f"{type(exc).__name__}: {exc}"
        )
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


async def process_text(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    message = update.message
    if message is None or not message.text:
        return
    text = message.text.strip()
    if not text:
        return

    if context.user_data.get("learn", False):
        append_learning_text(text)

    history = list(context.user_data.get("history", []))[-3:]
    status = await message.reply_text("🧠 Thinking…")
    try:
        started = time.perf_counter()
        response = await asyncio.to_thread(generate_text, text, history)
        elapsed = time.perf_counter() - started

        history.append((text, response))
        context.user_data["history"] = history[-3:]
        await status.edit_text(f"{response}\n\n({elapsed:.2f}s • local TinyGPT v5)")

        if context.user_data.get("voice", False):
            workdir = Path(tempfile.mkdtemp(prefix="viger_voice_"))
            try:
                voice_path = workdir / "reply.wav"
                await asyncio.to_thread(make_voice, response, voice_path)
                if voice_path.exists():
                    with voice_path.open("rb") as audio:
                        await message.reply_voice(voice=audio)
            except Exception as exc:
                await message.reply_text(f"🔊 Voice generation failed: {type(exc).__name__}: {exc}")
            finally:
                shutil.rmtree(workdir, ignore_errors=True)
    except Exception as exc:
        await status.edit_text(
            "🧠 TinyGPT could not generate a response.\n\n"
            f"{type(exc).__name__}: {exc}"
        )


def main() -> None:
    token = os.environ.get("VIGER_TELEGRAM_TOKEN") or input("Telegram bot token: ").strip()
    if not token:
        raise SystemExit("Telegram bot token is required.")

    application = Application.builder().token(token).build()
    application.add_handler(CommandHandler("start", start))
    application.add_handler(CommandHandler("help", help_command))
    application.add_handler(CommandHandler("status", status_command))
    application.add_handler(CommandHandler("learn", learn_command))
    application.add_handler(CommandHandler("voice", voice_command))
    application.add_handler(CommandHandler("train", train_command))
    application.add_handler(CommandHandler("teach", teach_command))
    application.add_handler(CallbackQueryHandler(callback))
    application.add_handler(MessageHandler(filters.PHOTO | filters.Document.IMAGE, process_image))
    application.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, process_text))
    print("[VIGER] Python-only Telegram bot is running. Ctrl+C to stop.")
    try:
        application.run_polling(allowed_updates=Update.ALL_TYPES)
    except Conflict:
        print("[VIGER] ERROR: another VIGER bot instance is already using this token. Stop it first.")
        raise SystemExit(2)


if __name__ == "__main__":
    main()
